### ISSUE TITLE
Way to add typings for custom scalars?

### ISSUE THREAD

**Issue by SkeLLLa** [mercurius-js/mercurius-typescript#11]
Hi. Is there any way or "recommended" way to add typings for custom scalars? For example, if I define new scalar `UUID` with resolver that verifies that it's really UUID. 
But in generated.ts those new scalars are typed as `any` so I'm searching the best way to pass there proper typings.

**Comment by PabloSzx** [comment]
You can use the "codegenConfig.scalars" option https://github.com/mercurius-js/mercurius-typescript/tree/master/packages/mercurius-codegen#options

**Comment by PabloSzx** [comment]
```ts
codegenMercurius(app, {
  targetPath: './src/graphql/generated.ts',
  codegenConfig: {
   scalars: {
      UUID: "string"
   }
  }
}).catch(console.error)
```

**Comment by SkeLLLa** [comment]
Thanks, looks like I've missed that part of doc.
