### ISSUE TITLE
Allow customization of internalResolversPrefix

### ISSUE THREAD

**Issue by DevelopmentByDavid** [mercurius-js/mercurius-typescript#14]
### Problem
Currently, `internalResolversPrefix` is overwritten. https://github.com/mercurius-js/mercurius-typescript/blob/58d9fa1a61854f13cde376308d31d15512018e02/packages/mercurius-codegen/src/code.ts#L82-L86

### Research/Background
I use `makeExecutableSchema` from `@graphql-tools/schema` -- the same as shown in the mercurius-js tests.  However, in the single test for unions I notice `makeExecutableSchema` is not used.  

https://github.com/mercurius-js/mercurius/blob/67f0fb31536a13274f8b9460556c3ca5a3dbc6cd/test/app-decorator.js#L808-L898

If I pass the schema with `resolveType` rather than `__resolveType`, then `makeExecutableSchema` will throw an error saying I must define `resolveType` within my schema (it thinks that `resolveType` is a field).  I can bypass the error by passing in the appropriate setting into `resolverValidationOptions`, but then I lose other types of errors/warnings, so I think this is suboptimal.

When I did bypass the error, `resolveType` did not work as expected with `mercurius-js` (the union did not resolve correctly). When I use `__resolveType` rather than `resolveType`, then the schema works as expected, but typescript gets angry.  

### Solution
I think the best solution is to allow users to overwrite the `internalResolversPrefix` setting.  

There may also be something wrong with the test in the `mercurius-js` repo, but I'm not sure.

**Comment by PabloSzx** [comment]
Fixed in the just released [v1.6.1](https://github.com/mercurius-js/mercurius-typescript/releases/tag/v1.6.1), thank you for reporting this issue/use-case
