### ISSUE TITLE
Override 'ParentType' in Mercurius loaders

### ISSUE THREAD

**Issue by Paol-imi** [mercurius-js/mercurius-typescript#17]
Hi, thanks for this amazing library!
Is there a way to override the Parent type in the Mercurius loaders?

for example, `@graphql-codegen/typescript-resolvers` generates and exports the types of the individual resolvers, so I'm able to import them and override the ParentType:

```ts
// generated.t.ts.
export type UserResolvers<ContextType, ParentType = ResolversParentTypes["User"]> = { ... };

export type Resolvers<ContextType = any> = {
  User?: UserResolvers<ContextType>;
  ...
};
```
and In my code:

```ts
import type { UserResolvers } from "./generated";

// My custom type.
type CustomParentType = { ... };

type Resolvers = {
  User?: UserResolvers<MercuriusContextType, CustomParentType>;
  ...
};
```

`Mercurius-codegen` seems to export only the type for the main loaders object, so I'm not able to override here.

```ts
// generated.t.ts.
export interface Loaders<TContext> {
  // Directly generates the type here.
  User?: { ... };
}
```

**Comment by PabloSzx** [comment]
@Paol-imi new configuration `loadersCustomParentTypes` added in v2.0.0, it can be used programmatically this way:

```ts
mercuriusCodegen(app, {
  targetPath: './src/graphql/generated.ts',
  codegenConfig: {
    loadersCustomParentTypes: {
      Human: 'Record<string,any>',
    },
  },
}).catch(console.error)
```

https://github.com/mercurius-js/mercurius-typescript/releases/tag/v2.0.0
