### ISSUE TITLE
Move prettier from dependencies -> devDependencies (mercurius-codegen)

### ISSUE THREAD

**Issue by sanjom** [mercurius-js/mercurius-typescript#18]
I have a slight issue in one of my projects, where I use a different prettier version to what is used here. Since it is a direct dependency of "mercurius-codegen", it ends up winning against my own prettier version.

Could you just move it to "devDependencies" to avoid such conflicts?

**Comment by PabloSzx** [comment]
https://github.com/mercurius-js/mercurius-typescript/releases/tag/3.0.0 Done in 3.0.0
