### ISSUE TITLE
mercurius-schema.json location in monorepo

### ISSUE THREAD

**Issue by keithkraker** [mercurius-js/mercurius-typescript#19]
I’m using mercurius inside of a monorepo where all projects are run from the root. This is causing my mercurius-schema.json file to be generated there instead of inside the project folder. It doesn’t look like it’s currently possible to specify a location for where this file is generated but would that be a difficult change? I think it would be nice to be able to specify its location like we can do for the the schema and documents location. Maybe it could be an option added to the PrebuildOptions interface? I dug through the src code but I’m not comfortable implementing this change myself.

**Comment by PabloSzx** [comment]
mercurius-codegen@3.1.0 released allowing to customize the prebuilt schema path https://github.com/mercurius-js/mercurius-typescript/releases/tag/3.1.0
