### ISSUE TITLE
codegen-gql-files: GraphQL files not copied to dist.

### ISSUE THREAD

**Issue by SkeLLLa** [mercurius-js/mercurius-typescript#7]
Example with codegen-gql-files tries to load files from "src" directory. If "src" directory is gone (e.g. not copied to production bundle) it will fail. Maybe it worth to use `__dirname` in example?

**Comment by PabloSzx** [comment]
The function "loadSchemaFiles" receives any string or array of strings, and the target is graphql files (basically plain text files), if your bundle doesn't include the src folder you would have to manually copy the text files to the dist, and the example code works as it is, you can check it being used in this template repo https://github.com/PabloSzx/next-fastify-mercurius-vercel

**Comment by PabloSzx** [comment]
Oh, and I forgot to point out that the fact of src not being bundled is covered up by the automatic mercurius-schema.json generation https://github.com/mercurius-js/mercurius-typescript/blob/master/examples/codegen-gql-files/mercurius-schema.json https://github.com/mercurius-js/mercurius-typescript/blob/master/packages/mercurius-codegen/src/schema.ts#L10, which makes it to work in Vercel deployments

**Comment by SkeLLLa** [comment]
@PabloSzx yes I can copy it manually, but it will still reference `src` folder unless you do the following:

```
const { schema } = loadSchemaFiles(path.join(__dirname, 'graphql/**/*.gql'), {
    watchOptions: {
      enabled: config.env === 'development',
      onChange(schema) {
        app.graphql.replaceSchema(buildSchema(schema.join('\n')));
        app.graphql.defineResolvers(resolvers);

        mercuriusCodegen(app, {
          targetPath: './src/graphql/generated.ts',
          operationsGlob: './src/graphql/operations/*.gql',
        }).catch(app.log.error);
      },
    },
  });
```

**Comment by PabloSzx** [comment]
I don't understand your point, all that code is targeted to be only executed while on development, you can see the "enabled" flag

**Comment by SkeLLLa** [comment]
If you try your example, build it, rename `src` directory to `_src` for example and then try to run it via `node dist/index.js` you'll receive an error that no graphql files found.

**Comment by PabloSzx** [comment]
By default if node_env is production and mercurius-schema.json exists, all the logic inside is ignored and uses the pre-built schema

**Comment by PabloSzx** [comment]
Because your NODE_ENV is not production...
