### ISSUE TITLE
Peer Dependency Warnings with fastify@5.x and mercurius@15.x in mercurius-codegen@5.0.5

### ISSUE THREAD

**Issue by acoBOYZ** [mercurius-js/mercurius-typescript#865]
Hello,

I am encountering peer dependency warnings when using mercurius-codegen@5.0.5 in my project with the following setup:

	•	fastify@5.0.0
	•	mercurius@15.0.0

The warnings are as follows:
```
WARN  Issues with peer dependencies found
.
└─┬ mercurius-codegen 5.0.5
  ├── ✕ unmet peer fastify@^4.26.2: found 5.0.0
  └── ✕ unmet peer mercurius@"^11.0.0 || ^12.0.0 || ^13.0.0 || ^14.0.0": found 15.0.0
```
It seems that mercurius-codegen does not yet support fastify@5.x and mercurius@15.x. Is there any plan to update the peer dependencies to support these newer versions, or should I downgrade to maintain compatibility? I’d prefer to stay on the latest versions to take advantage of new features and improvements.

Thank you for your time and for maintaining this library!

**Comment by PabloSzx** [comment]
will publish new version with the peer dependency update! everything should work as-is as I don't think there have been breaking changes

**Comment by PabloSzx** [comment]
[v6.0.0](https://github.com/mercurius-js/mercurius-typescript/releases/tag/mercurius-codegen%406.0.0) was just released bumping all the versions and seems to be working as expected, please confirm 💯

**Comment by acoBOYZ** [comment]
Perfect. Thank you
